---
kind: Deployment
apiVersion: apps/v1

metadata:
  name: fortune-deployment
  labels:
    app: fortune
    version: v1

spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortune-pod #Selector and template name need to match.
      version: v1
  template:
    metadata:
      name: fortune-pod
      namespace: myns
      labels:
        app: fortune-pod
        version: v1
    spec:
      containers:
      - name: fortune
        image: stackupiss/fortune:v1
        imagePullPolicy: Always
        ports:
        - name: app-port
          containerPort: 3000
