---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1

metadata:
  name: myapp-hps
  namespace: myns
  labels:
    name: myapp-hps

spec:
  maxReplicas: 4
  minReplicas: 1
  targetCPUUtilizationPercentage: 10
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: myapp-deploy