---
apiVersion: apps/v1
kind: Deployment

metadata:
   name: bgg-db
   namespace: bgg
   labels:
      app.kubernetes.io/name: bgg-db-deploy
      app.kubernetes.io/version: "1.0"
      app.kubernetes.io/part-of: bgg

spec:
   minReadySeconds: 60
   replicas: 1
   selector:
      matchLabels:
         app.kubernetes.io/name: bgg-db-pod
         app.kubernetes.io/version: "1.0"
   template:
      metadata:
         name: bgg-pod
         labels:
            app.kubernetes.io/name: bgg-db-pod
            app.kubernetes.io/version: "1.0"
            app.kubernetes.io/component: database
            app.kubernetes.io/part-of: bgg

      spec:
         containers:
         - name: bgg-container
           image: stackupiss/bgg-db:v1
           imagePullPolicy: Always
           env:
           - name: MYSQL_ROOT_PASSWORD
             value: changeit
           ports:
           - name: mysql-port
             containerPort: 3306
           livenessProbe:
              exec:
                 command:
                 - mysqladmin 
                 - ping 
                 - -uroot 
                 - -p$(MYSQL_ROOT_PASSWORD) 
                 - --silent 
              initialDelaySeconds: 60
              periodSeconds: 60

---

apiVersion: v1
kind: Service

metadata:
   name: bgg-db
   namespace: bgg
   labels:
      app.kubernetes.io/name: bgg-db-svc
      app.kubernetes.io/version: "1.0"
      app.kubernetes.io/part-of: bgg

spec:
   type: ClusterIP
   selector:
      app.kubernetes.io/name: bgg-db-pod
      app.kubernetes.io/version: "1.0"
   ports:
   - name: mysql-svc-port
     port: 3306
     targetPort: mysql-port

