apiVersion: apps/v1
kind: Deployment

metadata:
   name: bggdb-deploy
   labels:
      app: bggdb

spec:
   replicas: 1
   selector:
      matchLabels:
         app: bggdb
   minReadySeconds: 30
   template:
      metadata:
         name: bggdb-pod
         labels:
            app: bggdb
      spec:
         containers:
         - name: bggdb
           image: stackupiss/bgg-db:v1
           imagePullPolicy: IfNotPresent
           ports:
           - containerPort: 3306

---

apiVersion: v1
kind: Service

metadata:
   name: bggdb-svc

spec:
   selector:
      app: bggdb
   type: ClusterIP
   ports:
   - port: 3306
     targetPort: 3306
