

version: '3'

services: 

  app:
    build: ./server
    #image: myapp if image already available
    ports:
      - "3001:3000"
    environment:
      - DB_USER=root
      - DB_PASSWORD=changeit
      - DB_HOST=mydb
    networks: 
      - mynet
    depends_on:
      - mydb

  mydb:
    image: stackupiss/northwind-db:v1
    volumes:
      - myvol:/var/lib/mysql
    networks: 
      - mynet

networks:
  mynet:

volumes: 
  myvol:

